# Generated by Django 3.2 on 2023-04-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20230403_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='origianl_bag',
            new_name='original_bag',
        ),
    ]
